export const ICON_ASSETS = {
  meetUp: require('../../assets/icons/2x/meet_up.png'),
  locationPin: require('../../assets/icons/2x/location_pin.png'),
  milkBasket: require('../../assets/icons/2x/milk_basket.png'),
  pickUp: require('../../assets/icons/2x/pick_up.png'),
  scooterWithBasket: require('../../assets/icons/2x/scooter_with_basket.png'),
  accountVerified: require('../../assets/icons/2x/account_verified.png'),
  brokenHeart: require('../../assets/icons/2x/broken_heart.png'),
  office: require('../../assets/icons/2x/company_office.png'),
  couple: require('../../assets/icons/2x/couple.png'),
  divorced: require('../../assets/icons/2x/divorced.png'),
  female: require('../../assets/icons/2x/female.png'),
  genderOther: require('../../assets/icons/2x/gender_other.png'),
  google: require('../../assets/icons/2x/google.png'),
  heart: require('../../assets/icons/2x/heart.png'),
  home: require('../../assets/icons/2x/home.png'),
  information: require('../../assets/icons/2x/information.png'),
  list: require('../../assets/icons/2x/list.png'),
  male: require('../../assets/icons/2x/male.png'),
  phone: require('../../assets/icons/2x/phone.png'),
  receiveMilk: require('../../assets/icons/2x/receive_milk.png'),
  sendMilk: require('../../assets/icons/2x/send_milk.png'),
  separated: require('../../assets/icons/2x/separated.png'),
  single: require('../../assets/icons/2x/single.png'),
  townHall: require('../../assets/icons/2x/town_hall.png'),
  unknownBuilding: require('../../assets/icons/2x/unknown_building.png'),
  widowed: require('../../assets/icons/2x/widowed.png'),
};

export const IMAGE_ASSETS = {};
