packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - canvas
  - esbuild
  - postinstall-postinstall
  - protobufjs
  - react-native-nitro-modules
  - sharp
  - unrs-resolver
