packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - canvas
  - postinstall-postinstall
  - sharp
  - '@shopify/react-native-skia'
  - esbuild
  - react-native-nitro-modules
  - unrs-resolver
