/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * History of ownership transfers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MilkBagOwnershipHistory".
 */
export type MilkBagOwnershipHistory =
  | {
      previousOwner:
        | {
            relationTo: 'individuals';
            value: string | Individual;
          }
        | {
            relationTo: 'hospitals';
            value: string | Hospital;
          }
        | {
            relationTo: 'milkBanks';
            value: string | MilkBank;
          };
      newOwner:
        | {
            relationTo: 'individuals';
            value: string | Individual;
          }
        | {
            relationTo: 'hospitals';
            value: string | Hospital;
          }
        | {
            relationTo: 'milkBanks';
            value: string | MilkBank;
          };
      transferReason: 'DONATION_COMPLETED' | 'REDISTRIBUTION' | 'RETURN' | 'N/A';
      transferredAt?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProposedDelivery".
 */
export type ProposedDelivery =
  | {
      mode: 'PICKUP' | 'DELIVERY' | 'MEETUP';
      datetime?: string | null;
      address: string | Address;
      proposedBy:
        | {
            relationTo: 'individuals';
            value: string | Individual;
          }
        | {
            relationTo: 'hospitals';
            value: string | Hospital;
          }
        | {
            relationTo: 'milkBanks';
            value: string | MilkBank;
          };
      proposedAt: string;
      agreements?: DeliveryAgreements;
      id?: string | null;
    }[]
  | null;
/**
 * Delivery status for each notification channel (email, SMS, in-app, etc.). Tracks attempts, failures, and success.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NotificationChannelStats".
 */
export type NotificationChannelStats = {
  /**
   * Delivery method for this notification (e.g., email via Resend, SMS via Twilio, in-app display).
   */
  channel: string | NotificationChannel;
  /**
   * Whether this notification is scheduled for future delivery rather than immediate sending.
   */
  scheduled?: boolean | null;
  /**
   * Future date/time when this notification should be sent via this channel.
   */
  scheduledFor?: string | null;
  /**
   * Whether the notification was successfully delivered via this channel.
   */
  sent?: boolean | null;
  /**
   * Timestamp when the notification was successfully sent via this channel.
   */
  sentAt?: string | null;
  /**
   * Number of times delivery has been attempted via this channel. Includes both successful and failed attempts.
   */
  attempts?: number | null;
  /**
   * Timestamp of the most recent delivery attempt via this channel.
   */
  lastAttemptAt?: string | null;
  /**
   * Detailed error message explaining why delivery failed. Used for troubleshooting and retry logic.
   */
  failureReason?: string | null;
  id?: string | null;
}[];
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    addresses: Address;
    avatars: Avatar;
    barangays: Barangay;
    citiesMunicipalities: CityMunicipality;
    'delivery-preferences': DeliveryPreference;
    donations: Donation;
    hospitals: Hospital;
    images: Image;
    individuals: Individual;
    inventory: Inventory;
    islandGroups: IslandGroup;
    milkBags: MilkBag;
    'milk-bag-images': MilkBagImage;
    milkBanks: MilkBank;
    notificationCategories: NotificationCategory;
    notificationChannels: NotificationChannel;
    notifications: Notification;
    notificationTypes: NotificationType;
    provinces: Province;
    regions: Region;
    requests: Request;
    users: User;
    transactions: Transaction;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    addresses: {
      deliveryPreferences: 'delivery-preferences';
    };
    'delivery-preferences': {
      donations: 'donations';
      requests: 'requests';
    };
    donations: {
      transactions: 'transactions';
    };
    milkBags: {
      donation: 'donations';
      request: 'requests';
    };
    requests: {
      transactions: 'transactions';
    };
    users: {
      addresses: 'addresses';
      deliveryPreferences: 'delivery-preferences';
    };
  };
  collectionsSelect: {
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    avatars: AvatarsSelect<false> | AvatarsSelect<true>;
    barangays: BarangaysSelect<false> | BarangaysSelect<true>;
    citiesMunicipalities: CitiesMunicipalitiesSelect<false> | CitiesMunicipalitiesSelect<true>;
    'delivery-preferences': DeliveryPreferencesSelect<false> | DeliveryPreferencesSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    hospitals: HospitalsSelect<false> | HospitalsSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    individuals: IndividualsSelect<false> | IndividualsSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    islandGroups: IslandGroupsSelect<false> | IslandGroupsSelect<true>;
    milkBags: MilkBagsSelect<false> | MilkBagsSelect<true>;
    'milk-bag-images': MilkBagImagesSelect<false> | MilkBagImagesSelect<true>;
    milkBanks: MilkBanksSelect<false> | MilkBanksSelect<true>;
    notificationCategories: NotificationCategoriesSelect<false> | NotificationCategoriesSelect<true>;
    notificationChannels: NotificationChannelsSelect<false> | NotificationChannelsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    notificationTypes: NotificationTypesSelect<false> | NotificationTypesSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Addresses of users, which are used to identify locations for various purposes such as shipping and identification.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  owner?: (string | null) | User;
  /**
   * e.g. Home, Workplace.
   */
  name?: string | null;
  /**
   * Set as default address.
   */
  isDefault?: boolean | null;
  /**
   * Postal/Zip code of the address.
   */
  zipCode?: string | null;
  province: string | Province;
  cityMunicipality: string | CityMunicipality;
  barangay?: (string | null) | Barangay;
  street?: string | null;
  displayName?: string | null;
  region?: (string | null) | Region;
  islandGroup?: (string | null) | IslandGroup;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  deliveryPreferences?: {
    docs?: (string | DeliveryPreference)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role?: ('AUTHENTICATED' | 'ADMIN') | null;
  email: string;
  phone?: string | null;
  profileType?: ('INDIVIDUAL' | 'HOSPITAL' | 'MILK_BANK') | null;
  profile?:
    | ({
        relationTo: 'individuals';
        value: string | Individual;
      } | null)
    | ({
        relationTo: 'milkBanks';
        value: string | MilkBank;
      } | null)
    | ({
        relationTo: 'hospitals';
        value: string | Hospital;
      } | null);
  addresses?: {
    docs?: (string | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  deliveryPreferences?: {
    docs?: (string | DeliveryPreference)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  lastSignInAt?: string | null;
  emailConfirmedAt?: string | null;
  phoneConfirmedAt?: string | null;
  picture?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individuals profile of users, including their personal information such as name, date of birth, contact details, and other relevant attributes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "individuals".
 */
export interface Individual {
  id: string;
  displayName?: string | null;
  owner?: (string | null) | User;
  avatar?: (string | null) | Avatar;
  givenName: string;
  middleName?: string | null;
  familyName: string;
  birth: string;
  phone?: string | null;
  dependents?: number | null;
  gender: 'MALE' | 'FEMALE' | 'OTHER';
  maritalStatus: 'SINGLE' | 'MARRIED' | 'SEPARATED' | 'WIDOWED' | 'DIVORCED' | 'N/A';
  updatedAt: string;
  createdAt: string;
}
/**
 * Avatars are images used to represent users in the system. They can be uploaded by users themselves or by administrators.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars".
 */
export interface Avatar {
  id: string;
  alt?: string | null;
  /**
   * A string that represents a blurred version of the image.
   */
  blurHash?: string | null;
  owner?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    icon?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Milk Bank profile of users, including their details such as name, type, head, and contact information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milkBanks".
 */
export interface MilkBank {
  id: string;
  owner?: (string | null) | User;
  avatar?: (string | null) | Avatar;
  name: string;
  description?: string | null;
  /**
   * Head or president of the milk bank.
   */
  head?: string | null;
  type?: ('GOVERNMENT' | 'PRIVATE' | 'OTHER') | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hospital profile of users, including their details such as name, type, head, and contact information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals".
 */
export interface Hospital {
  id: string;
  owner?: (string | null) | User;
  avatar?: (string | null) | Avatar;
  name: string;
  description?: string | null;
  /**
   * Head or president of the hospital.
   */
  head?: string | null;
  hospitalID?: string | null;
  type?: ('GOVERNMENT' | 'PRIVATE' | 'OTHER') | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-preferences".
 */
export interface DeliveryPreference {
  id: string;
  createdBy?: (string | null) | User;
  owner?: (string | null) | User;
  name?: string | null;
  /**
   * Preferred delivery modes of the individual. This will be used for matching.
   */
  preferredMode: ('PICKUP' | 'DELIVERY' | 'MEETUP')[];
  /**
   * Address available for pickup, delivery, or meet-up.
   */
  address: string | Address;
  /**
   * Days available for pickup, delivery, or meet-up.
   */
  availableDays: ('MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY')[];
  donations?: {
    docs?: (string | Donation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  requests?: {
    docs?: (string | Request)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: string;
  /**
   * Title of the donation record.
   */
  title?: string | null;
  /**
   * Total volume of milk donated.
   */
  volume?: number | null;
  /**
   * Volume still available for allocation
   */
  remainingVolume?: number | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  rejectedAt?: string | null;
  expiredAt?: string | null;
  createdBy?: (string | null) | User;
  /**
   * The person donating the milk
   */
  donor: string | Individual;
  /**
   * Intended recipient for this donation (optional - leave empty for general donation)
   */
  recipient?:
    | ({
        relationTo: 'individuals';
        value: string | Individual;
      } | null)
    | ({
        relationTo: 'hospitals';
        value: string | Hospital;
      } | null)
    | ({
        relationTo: 'milkBanks';
        value: string | MilkBank;
      } | null);
  status: 'PENDING' | 'AVAILABLE' | 'MATCHED' | 'COMPLETED' | 'EXPIRED' | 'CANCELLED' | 'REJECTED';
  details: {
    /**
     * Type of storage for the milk
     */
    storageType: 'FRESH' | 'FROZEN';
    /**
     * How the milk was collected
     */
    collectionMode: 'MANUAL' | 'MANUAL_PUMP' | 'ELECTRIC_PUMP';
    /**
     * Select the milk bags used for this donation
     */
    bags: (string | MilkBag)[];
    /**
     * Upload images of the milk sample
     */
    milkSample?: (string | Image)[] | null;
    /**
     * Additional notes or special instructions from donor
     */
    notes?: string | null;
  };
  /**
   * Delivery preferences for the milk
   */
  deliveryPreferences?: (string | DeliveryPreference)[] | null;
  /**
   * Transactions associated with this donation
   */
  transactions?: {
    docs?: (string | Transaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milkBags".
 */
export interface MilkBag {
  id: string;
  code?: string | null;
  title?: string | null;
  createdBy?: (string | null) | User;
  /**
   * The individual donating the milk bag
   */
  donor: string | Individual;
  /**
   * Current owner of the milk bag
   */
  owner:
    | {
        relationTo: 'individuals';
        value: string | Individual;
      }
    | {
        relationTo: 'hospitals';
        value: string | Hospital;
      }
    | {
        relationTo: 'milkBanks';
        value: string | MilkBank;
      };
  /**
   * Volume of milk in milliliters
   */
  volume: number;
  /**
   * Current status of the milk bag
   */
  status: 'DRAFT' | 'AVAILABLE' | 'ALLOCATED' | 'CONSUMED' | 'EXPIRED' | 'DISCARDED';
  /**
   * Date when the milk was collected
   */
  collectedAt: string;
  /**
   * Date when the milk expires
   */
  expiresAt?: string | null;
  /**
   * Upload a photo showing the milk bag with the code clearly visible. This can be added after initial creation.
   */
  bagImage?: (string | null) | MilkBagImage;
  ownershipHistory?: MilkBagOwnershipHistory;
  /**
   * The donation this milk bag is part of
   */
  donation?: {
    docs?: (string | Donation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * The request this milk bag fulfills.
   */
  request?: {
    docs?: (string | Request)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milk-bag-images".
 */
export interface MilkBagImage {
  id: string;
  alt?: string | null;
  /**
   * A string that represents a blurred version of the image.
   */
  blurHash?: string | null;
  createdBy?: (string | null) | User;
  owner?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: string;
  /**
   * Title of the milk request.
   */
  title?: string | null;
  /**
   * Percentage of the request that has been fulfilled.
   */
  fulfillmentPercentage?: number | null;
  /**
   * Initial volume needed for the request, used for calculations.
   */
  initialVolumeNeeded?: number | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  rejectedAt?: string | null;
  expiredAt?: string | null;
  createdBy?: (string | null) | User;
  /**
   * The person requesting the milk
   */
  requester: string | Individual;
  /**
   * Who this request is directed to (optional - leave empty for general request)
   */
  recipient?:
    | ({
        relationTo: 'individuals';
        value: string | Individual;
      } | null)
    | ({
        relationTo: 'hospitals';
        value: string | Hospital;
      } | null)
    | ({
        relationTo: 'milkBanks';
        value: string | MilkBank;
      } | null);
  /**
   * Amount of milk needed in milliliters
   */
  volumeNeeded: number;
  /**
   * Amount of milk already fulfilled in milliliters
   */
  volumeFulfilled?: number | null;
  status: 'PENDING' | 'AVAILABLE' | 'MATCHED' | 'COMPLETED' | 'EXPIRED' | 'CANCELLED' | 'REJECTED';
  details: {
    /**
     * Date when the milk is needed
     */
    neededAt: string;
    /**
     * Preferred storage type
     */
    storagePreference?: ('FRESH' | 'FROZEN' | 'EITHER') | null;
    urgency: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    /**
     * Milk bags that fulfilled this request. If empty, it means the request is still pending.
     */
    bags?: (string | MilkBag)[] | null;
    /**
     * Image of the person or baby receiving the milk
     */
    image?: (string | null) | Image;
    /**
     * Reason for requesting milk donation
     */
    reason?: string | null;
    /**
     * Additional notes or special instructions from requester
     */
    notes?: string | null;
  };
  /**
   * Delivery preferences for the milk
   */
  deliveryPreferences?: (string | DeliveryPreference)[] | null;
  /**
   * Transactions associated with this donation
   */
  transactions?: {
    docs?: (string | Transaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: string;
  alt?: string | null;
  /**
   * A string that represents a blurred version of the image.
   */
  blurHash?: string | null;
  createdBy?: (string | null) | User;
  owner?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  /**
   * Unique transaction identifier
   */
  transactionNumber?: string | null;
  createdBy?: (string | null) | User;
  donation?: (string | null) | Donation;
  request?: (string | null) | Request;
  sender:
    | {
        relationTo: 'individuals';
        value: string | Individual;
      }
    | {
        relationTo: 'hospitals';
        value: string | Hospital;
      }
    | {
        relationTo: 'milkBanks';
        value: string | MilkBank;
      };
  recipient:
    | {
        relationTo: 'individuals';
        value: string | Individual;
      }
    | {
        relationTo: 'hospitals';
        value: string | Hospital;
      }
    | {
        relationTo: 'milkBanks';
        value: string | MilkBank;
      };
  status:
    | 'MATCHED'
    | 'PENDING_DELIVERY_CONFIRMATION'
    | 'DELIVERY_SCHEDULED'
    | 'IN_TRANSIT'
    | 'READY_FOR_PICKUP'
    | 'DELIVERED'
    | 'COMPLETED'
    | 'FAILED'
    | 'CANCELLED';
  /**
   * Volume of milk being matched (in mL)
   */
  matchedVolume: number;
  /**
   * Type of transaction (determines delivery workflow)
   */
  transactionType: 'P2P' | 'P2O' | 'O2P';
  /**
   * Milk bags included in this transaction
   */
  matchedBags: (string | MilkBag)[];
  delivery?: Delivery;
  tracking?: {
    deliveredAt?: string | null;
    completedAt?: string | null;
    failedAt?: string | null;
    failureReason?: string | null;
    cancelledAt?: string | null;
    cancelReason?: string | null;
    statusHistory?:
      | {
          /**
           * Status of the transaction at this point in time
           */
          status:
            | 'MATCHED'
            | 'PENDING_DELIVERY_CONFIRMATION'
            | 'DELIVERY_SCHEDULED'
            | 'IN_TRANSIT'
            | 'READY_FOR_PICKUP'
            | 'DELIVERED'
            | 'COMPLETED'
            | 'FAILED'
            | 'CANCELLED';
          /**
           * Timestamp when this status was recorded
           */
          timestamp: string;
          /**
           * Any additional notes related to this status change
           */
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Delivery".
 */
export interface Delivery {
  proposedDelivery?: ProposedDelivery;
  confirmedDelivery?: ConfirmedDelivery;
  instructions?: string | null;
}
/**
 * Tracks delivery proposal agreement status from both parties
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeliveryAgreements".
 */
export interface DeliveryAgreements {
  sender?: {
    agreed?: boolean | null;
    agreedBy?:
      | ({
          relationTo: 'individuals';
          value: string | Individual;
        } | null)
      | ({
          relationTo: 'hospitals';
          value: string | Hospital;
        } | null)
      | ({
          relationTo: 'milkBanks';
          value: string | MilkBank;
        } | null);
    agreedAt?: string | null;
  };
  recipient?: {
    agreed?: boolean | null;
    agreedBy?:
      | ({
          relationTo: 'individuals';
          value: string | Individual;
        } | null)
      | ({
          relationTo: 'hospitals';
          value: string | Hospital;
        } | null)
      | ({
          relationTo: 'milkBanks';
          value: string | MilkBank;
        } | null);
    agreedAt?: string | null;
  };
  /**
   * Automatically checked when both sender and recipient have agreed
   */
  bothAgreed?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConfirmedDelivery".
 */
export interface ConfirmedDelivery {
  mode: 'PICKUP' | 'DELIVERY' | 'MEETUP';
  datetime?: string | null;
  address: string | Address;
  confirmedAt: string;
}
/**
 * Provinces in the Philippines, which are administrative divisions that group cities and municipalities.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: string;
  name: string;
  code: string;
  region: string | Region;
  islandGroup: string | IslandGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * Regions in the Philippines, which are administrative divisions that group provinces and cities/municipalities.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: string;
  name: string;
  code: string;
  regionName?: string | null;
  islandGroup: string | IslandGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * Island groups in the Philippines, which are collections of islands that share geographical and cultural characteristics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islandGroups".
 */
export interface IslandGroup {
  id: string;
  name: string;
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cities and municipalities in the Philippines, including their details such as name, code, type, and associated regions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "citiesMunicipalities".
 */
export interface CityMunicipality {
  id: string;
  name: string;
  oldName?: string | null;
  isCapital: boolean;
  code: string;
  type: 'NONE' | 'CITY' | 'MUNICIPALITY';
  districtCode?: string | null;
  province?: (string | null) | Province;
  region: string | Region;
  islandGroup: string | IslandGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * Barangays in the Philippines, including their details such as name, code, and associated city/municipality, province, region, and island group.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barangays".
 */
export interface Barangay {
  id: string;
  name: string;
  oldName?: string | null;
  code: string;
  subMunicipalityCode?: string | null;
  districtCode?: string | null;
  cityMunicipality?: (string | null) | CityMunicipality;
  province?: (string | null) | Province;
  region: string | Region;
  islandGroup: string | IslandGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: string;
  organization:
    | {
        relationTo: 'hospitals';
        value: string | Hospital;
      }
    | {
        relationTo: 'milkBanks';
        value: string | MilkBank;
      };
  /**
   * Original donation that created this inventory
   */
  sourceDonation?: (string | null) | Donation;
  /**
   * Initial volume received into inventory (may differ from donation volume)
   */
  initialVolume: number;
  /**
   * Volume still available for use in milliliters
   */
  remainingVolume: number;
  status: 'AVAILABLE' | 'RESERVED' | 'EXPIRED' | 'CONSUMED';
  /**
   * Milk bags in this inventory
   */
  milkBags: (string | MilkBag)[];
  /**
   * When the organization received this donation
   */
  receivedAt?: string | null;
  /**
   * When this inventory item expires
   */
  expiresAt?: string | null;
  /**
   * Additional notes about this inventory item
   */
  notes?: string | null;
  /**
   * Details about how this inventory was allocated to requests
   */
  allocationDetails?:
    | {
        request: string | Request;
        /**
         * Milk bags allocated to this request
         */
        allocatedBags: (string | MilkBag)[];
        /**
         * Unique identifier for grouping allocations that fulfill the same request. (Auto generated)
         */
        allocationId?: string | null;
        allocatedAt?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize notification types into logical categories with consistent styling and behavior.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationCategories".
 */
export interface NotificationCategory {
  id: string;
  /**
   * Unique identifier used in code to reference this category. Use UPPERCASE with underscores (e.g., MATCHING, DELIVERY_STATUS, SYSTEM_ALERTS)
   */
  key: string;
  /**
   * Human-readable name displayed in the admin interface and potentially in user-facing UI
   */
  name: string;
  /**
   * Detailed description of what types of notifications belong to this category. Helps admins understand when to use this category.
   */
  description?: string | null;
  /**
   * Icon name for the notification icon. Only supports icon names from Lucide.dev as of the current version. Please refer to the Lucide.dev documentation for available icons.
   */
  icon?: string | null;
  /**
   * Hex color code used for UI elements like badges, icons, and category indicators. Should follow your design system colors.
   */
  color?: string | null;
  /**
   * Controls the order categories appear in lists and dropdowns. Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Whether this category is currently active. Inactive categories cannot be assigned to new notification types but existing notifications remain unchanged.
   */
  active?: boolean | null;
  /**
   * Additional settings and information for this category
   */
  metadata?: {
    /**
     * Whether users can customize notification preferences for this category (e.g., enable/disable, choose delivery channels)
     */
    allowUserSettings?: boolean | null;
    /**
     * How long notifications in this category should be kept before automatic cleanup. System notifications may have longer retention.
     */
    retentionDays?: number | null;
  };
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure delivery channels for sending notifications through different mediums (email, SMS, push, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationChannels".
 */
export interface NotificationChannel {
  id: string;
  createdBy?: (string | null) | User;
  /**
   * Unique identifier used in code (e.g., RESEND_EMAIL, TWILIO_SMS, IN_APP_REAL_TIME)
   */
  key: string;
  /**
   * Human-readable name displayed in admin and user preferences
   */
  name: string;
  /**
   * The delivery method this channel uses. Determines available configuration options.
   */
  type: 'IN_APP' | 'EMAIL' | 'SMS' | 'PUSH' | 'WEBHOOK' | 'EXTERNAL_API';
  /**
   * Purpose and configuration notes for this channel
   */
  description?: string | null;
  /**
   * Whether this channel is currently active and available for notifications
   */
  active?: boolean | null;
  configuration?: {
    /**
     * API endpoint URL for HTTP POST notifications (must be HTTPS)
     */
    endpoint?: string | null;
    /**
     * API key for external service authentication
     */
    apiKey?: string | null;
    /**
     * Email-specific settings that override PayloadCMS defaults
     */
    emailConfig?: {
      /**
       * Email address notifications are sent from (optional)
       */
      fromAddress?: string | null;
      /**
       * Display name shown to recipients (optional)
       */
      fromName?: string | null;
      /**
       * Email address for replies (recommended)
       */
      replyTo?: string | null;
    };
  };
  templates?: {
    /**
     * Subject line with variables: {{title}}, {{recipientName}}, {{priority}}
     */
    subject?: string | null;
    /**
     * Raw HTML template with variables. Available: {{title}}, {{message}}, {{recipientName}}, {{actionUrl}}, {{actionLabel}}, {{priority}}
     */
    htmlTemplate?: string | null;
    /**
     * Plain text fallback for email clients that don't support HTML
     */
    textTemplate?: string | null;
    /**
     * SMS template (keep concise, ~160 characters max for single SMS)
     */
    smsTemplate?: string | null;
  };
  delivery?: {
    /**
     * Automatic retry behavior for failed deliveries
     */
    retrySettings?: {
      /**
       * Number of times to retry failed deliveries (0 = no retries)
       */
      maxRetries?: number | null;
      /**
       * Minutes to wait between retry attempts
       */
      retryDelay?: number | null;
      strategy?: ('FIXED' | 'EXPONENTIAL' | 'LINEAR') | null;
    };
    /**
     * Additional settings for channel management
     */
    metadata?: {
      /**
       * Priority when multiple channels of same type exist (lower = higher priority)
       */
      priority?: number | null;
      /**
       * Maximum notifications per hour (leave empty for no limit)
       */
      rateLimitPerHour?: number | null;
      /**
       * Comma-separated tags for organization (e.g., production, urgent, marketing)
       */
      tags?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual notification instances with delivery tracking and user interaction data
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  createdBy?: (string | null) | User;
  /**
   * User who will receive this notification. Determines delivery preferences and contact methods.
   */
  recipient: string | User;
  /**
   * Template and configuration used to generate this notification. Defines category, priority, and available channels.
   */
  notificationType: string | NotificationType;
  /**
   * Overrides the default priority from notification type. Affects delivery urgency and user interface prominence.
   */
  priority?: ('LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL') | null;
  /**
   * Final processed title from notification type template with variables replaced. This is what users see as the notification headline.
   */
  title: string;
  /**
   * Final processed message content from template with variables replaced. Contains the main notification text users will read.
   */
  message: string;
  /**
   * Key-value pairs of variables used to process the notification templates. Stored for audit trail and debugging purposes.
   */
  variables?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Whether the recipient has marked this notification as read. Updates automatically when user views notification.
   */
  read?: boolean | null;
  /**
   * Timestamp when the notification was marked as read by the recipient.
   */
  readAt?: string | null;
  relatedData?: {
    /**
     * System entity that triggered this notification (e.g., matched donation, completed delivery). Used for context and navigation.
     */
    data?:
      | ({
          relationTo: 'requests';
          value: string | Request;
        } | null)
      | ({
          relationTo: 'donations';
          value: string | Donation;
        } | null);
    /**
     * URL for the primary action button in the notification. Typically links to relevant page in the app.
     */
    actionUrl?: string | null;
    /**
     * Text displayed on the action button. Should clearly indicate what the action does.
     */
    actionLabel?: string | null;
  };
  delivery: {
    channelsStats: NotificationChannelStats;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationTypes".
 */
export interface NotificationType {
  id: string;
  /**
   * Whether this notification type is currently active
   */
  active?: boolean | null;
  /**
   * Default channels for this notification type
   */
  defaultChannels?: (string | NotificationChannel)[] | null;
  createdBy?: (string | null) | User;
  /**
   * Unique identifier for this notification type (e.g., DONATION_MATCHED)
   */
  key: string;
  /**
   * Human-readable name for this notification type
   */
  name: string;
  /**
   * Description of when this notification is triggered
   */
  description?: string | null;
  /**
   * Category this notification type belongs to
   */
  category: string | NotificationCategory;
  /**
   * Priority level of this notification type
   */
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  trigger: NotificationTypeTrigger;
  template: NotificationTypeTemplate;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NotificationTypeTrigger".
 */
export interface NotificationTypeTrigger {
  collection: 'requests' | 'donations' | 'deliveries' | 'system';
  event: 'CREATE' | 'UPDATE' | 'DELETE';
  /**
   * JSON conditions for when to trigger this notification. Use "exists" to check for field existence, "changed" to check for changes, or direct value matches.
   */
  conditions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NotificationTypeTemplate".
 */
export interface NotificationTypeTemplate {
  /**
   * Title template with variables like {{volume}}, {{date}}
   */
  title: string;
  /**
   * Message template with variables
   */
  message: string;
  /**
   * URL to redirect user when they click the notification. Use {{id}} for dynamic IDs.
   */
  actionUrl?: string | null;
  /**
   * Text for the action button in the notification
   */
  actionLabel?: string | null;
  variables?:
    | {
        /**
         * Whether this variable is required
         */
        required?: boolean | null;
        /**
         * Key for this variable, used in templates like {{volume}}
         */
        key: string;
        /**
         * Expected data type for this variable (optional)
         */
        type: 'string' | 'number' | 'boolean' | 'date' | 'array' | 'object';
        /**
         * Path to the data in the document, e.g. donor.displayName or request.volume. Make sure the path exists in the document and holds the value of the variable.
         */
        path?: string | null;
        /**
         * Default value if not provided (optional)
         */
        defaultValue?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'avatars';
        value: string | Avatar;
      } | null)
    | ({
        relationTo: 'barangays';
        value: string | Barangay;
      } | null)
    | ({
        relationTo: 'citiesMunicipalities';
        value: string | CityMunicipality;
      } | null)
    | ({
        relationTo: 'delivery-preferences';
        value: string | DeliveryPreference;
      } | null)
    | ({
        relationTo: 'donations';
        value: string | Donation;
      } | null)
    | ({
        relationTo: 'hospitals';
        value: string | Hospital;
      } | null)
    | ({
        relationTo: 'images';
        value: string | Image;
      } | null)
    | ({
        relationTo: 'individuals';
        value: string | Individual;
      } | null)
    | ({
        relationTo: 'inventory';
        value: string | Inventory;
      } | null)
    | ({
        relationTo: 'islandGroups';
        value: string | IslandGroup;
      } | null)
    | ({
        relationTo: 'milkBags';
        value: string | MilkBag;
      } | null)
    | ({
        relationTo: 'milk-bag-images';
        value: string | MilkBagImage;
      } | null)
    | ({
        relationTo: 'milkBanks';
        value: string | MilkBank;
      } | null)
    | ({
        relationTo: 'notificationCategories';
        value: string | NotificationCategory;
      } | null)
    | ({
        relationTo: 'notificationChannels';
        value: string | NotificationChannel;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'notificationTypes';
        value: string | NotificationType;
      } | null)
    | ({
        relationTo: 'provinces';
        value: string | Province;
      } | null)
    | ({
        relationTo: 'regions';
        value: string | Region;
      } | null)
    | ({
        relationTo: 'requests';
        value: string | Request;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  isDefault?: T;
  zipCode?: T;
  province?: T;
  cityMunicipality?: T;
  barangay?: T;
  street?: T;
  displayName?: T;
  region?: T;
  islandGroup?: T;
  coordinates?: T;
  deliveryPreferences?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars_select".
 */
export interface AvatarsSelect<T extends boolean = true> {
  alt?: T;
  blurHash?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        icon?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barangays_select".
 */
export interface BarangaysSelect<T extends boolean = true> {
  name?: T;
  oldName?: T;
  code?: T;
  subMunicipalityCode?: T;
  districtCode?: T;
  cityMunicipality?: T;
  province?: T;
  region?: T;
  islandGroup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "citiesMunicipalities_select".
 */
export interface CitiesMunicipalitiesSelect<T extends boolean = true> {
  name?: T;
  oldName?: T;
  isCapital?: T;
  code?: T;
  type?: T;
  districtCode?: T;
  province?: T;
  region?: T;
  islandGroup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-preferences_select".
 */
export interface DeliveryPreferencesSelect<T extends boolean = true> {
  createdBy?: T;
  owner?: T;
  name?: T;
  preferredMode?: T;
  address?: T;
  availableDays?: T;
  donations?: T;
  requests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  title?: T;
  volume?: T;
  remainingVolume?: T;
  completedAt?: T;
  cancelledAt?: T;
  rejectedAt?: T;
  expiredAt?: T;
  createdBy?: T;
  donor?: T;
  recipient?: T;
  status?: T;
  details?:
    | T
    | {
        storageType?: T;
        collectionMode?: T;
        bags?: T;
        milkSample?: T;
        notes?: T;
      };
  deliveryPreferences?: T;
  transactions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals_select".
 */
export interface HospitalsSelect<T extends boolean = true> {
  owner?: T;
  avatar?: T;
  name?: T;
  description?: T;
  head?: T;
  hospitalID?: T;
  type?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  blurHash?: T;
  createdBy?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "individuals_select".
 */
export interface IndividualsSelect<T extends boolean = true> {
  displayName?: T;
  owner?: T;
  avatar?: T;
  givenName?: T;
  middleName?: T;
  familyName?: T;
  birth?: T;
  phone?: T;
  dependents?: T;
  gender?: T;
  maritalStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  organization?: T;
  sourceDonation?: T;
  initialVolume?: T;
  remainingVolume?: T;
  status?: T;
  milkBags?: T;
  receivedAt?: T;
  expiresAt?: T;
  notes?: T;
  allocationDetails?:
    | T
    | {
        request?: T;
        allocatedBags?: T;
        allocationId?: T;
        allocatedAt?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islandGroups_select".
 */
export interface IslandGroupsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milkBags_select".
 */
export interface MilkBagsSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  createdBy?: T;
  donor?: T;
  owner?: T;
  volume?: T;
  status?: T;
  collectedAt?: T;
  expiresAt?: T;
  bagImage?: T;
  ownershipHistory?: T | MilkBagOwnershipHistorySelect<T>;
  donation?: T;
  request?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MilkBagOwnershipHistory_select".
 */
export interface MilkBagOwnershipHistorySelect<T extends boolean = true> {
  previousOwner?: T;
  newOwner?: T;
  transferReason?: T;
  transferredAt?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milk-bag-images_select".
 */
export interface MilkBagImagesSelect<T extends boolean = true> {
  alt?: T;
  blurHash?: T;
  createdBy?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milkBanks_select".
 */
export interface MilkBanksSelect<T extends boolean = true> {
  owner?: T;
  avatar?: T;
  name?: T;
  description?: T;
  head?: T;
  type?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationCategories_select".
 */
export interface NotificationCategoriesSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  description?: T;
  icon?: T;
  color?: T;
  sortOrder?: T;
  active?: T;
  metadata?:
    | T
    | {
        allowUserSettings?: T;
        retentionDays?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationChannels_select".
 */
export interface NotificationChannelsSelect<T extends boolean = true> {
  createdBy?: T;
  key?: T;
  name?: T;
  type?: T;
  description?: T;
  active?: T;
  configuration?:
    | T
    | {
        endpoint?: T;
        apiKey?: T;
        emailConfig?:
          | T
          | {
              fromAddress?: T;
              fromName?: T;
              replyTo?: T;
            };
      };
  templates?:
    | T
    | {
        subject?: T;
        htmlTemplate?: T;
        textTemplate?: T;
        smsTemplate?: T;
      };
  delivery?:
    | T
    | {
        retrySettings?:
          | T
          | {
              maxRetries?: T;
              retryDelay?: T;
              strategy?: T;
            };
        metadata?:
          | T
          | {
              priority?: T;
              rateLimitPerHour?: T;
              tags?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  createdBy?: T;
  recipient?: T;
  notificationType?: T;
  priority?: T;
  title?: T;
  message?: T;
  variables?: T;
  read?: T;
  readAt?: T;
  relatedData?:
    | T
    | {
        data?: T;
        actionUrl?: T;
        actionLabel?: T;
      };
  delivery?:
    | T
    | {
        channelsStats?: T | NotificationChannelStatsSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NotificationChannelStats_select".
 */
export interface NotificationChannelStatsSelect<T extends boolean = true> {
  channel?: T;
  scheduled?: T;
  scheduledFor?: T;
  sent?: T;
  sentAt?: T;
  attempts?: T;
  lastAttemptAt?: T;
  failureReason?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationTypes_select".
 */
export interface NotificationTypesSelect<T extends boolean = true> {
  active?: T;
  defaultChannels?: T;
  createdBy?: T;
  key?: T;
  name?: T;
  description?: T;
  category?: T;
  priority?: T;
  trigger?: T | NotificationTypeTriggerSelect<T>;
  template?: T | NotificationTypeTemplateSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NotificationTypeTrigger_select".
 */
export interface NotificationTypeTriggerSelect<T extends boolean = true> {
  collection?: T;
  event?: T;
  conditions?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NotificationTypeTemplate_select".
 */
export interface NotificationTypeTemplateSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  actionUrl?: T;
  actionLabel?: T;
  variables?:
    | T
    | {
        required?: T;
        key?: T;
        type?: T;
        path?: T;
        defaultValue?: T;
        description?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  region?: T;
  islandGroup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  regionName?: T;
  islandGroup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  title?: T;
  fulfillmentPercentage?: T;
  initialVolumeNeeded?: T;
  completedAt?: T;
  cancelledAt?: T;
  rejectedAt?: T;
  expiredAt?: T;
  createdBy?: T;
  requester?: T;
  recipient?: T;
  volumeNeeded?: T;
  volumeFulfilled?: T;
  status?: T;
  details?:
    | T
    | {
        neededAt?: T;
        storagePreference?: T;
        urgency?: T;
        bags?: T;
        image?: T;
        reason?: T;
        notes?: T;
      };
  deliveryPreferences?: T;
  transactions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  email?: T;
  phone?: T;
  profileType?: T;
  profile?: T;
  addresses?: T;
  deliveryPreferences?: T;
  lastSignInAt?: T;
  emailConfirmedAt?: T;
  phoneConfirmedAt?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  transactionNumber?: T;
  createdBy?: T;
  donation?: T;
  request?: T;
  sender?: T;
  recipient?: T;
  status?: T;
  matchedVolume?: T;
  transactionType?: T;
  matchedBags?: T;
  delivery?: T | DeliverySelect<T>;
  tracking?:
    | T
    | {
        deliveredAt?: T;
        completedAt?: T;
        failedAt?: T;
        failureReason?: T;
        cancelledAt?: T;
        cancelReason?: T;
        statusHistory?:
          | T
          | {
              status?: T;
              timestamp?: T;
              notes?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Delivery_select".
 */
export interface DeliverySelect<T extends boolean = true> {
  proposedDelivery?: T | ProposedDeliverySelect<T>;
  confirmedDelivery?: T | ConfirmedDeliverySelect<T>;
  instructions?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProposedDelivery_select".
 */
export interface ProposedDeliverySelect<T extends boolean = true> {
  mode?: T;
  datetime?: T;
  address?: T;
  proposedBy?: T;
  proposedAt?: T;
  agreements?: T | DeliveryAgreementsSelect<T>;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeliveryAgreements_select".
 */
export interface DeliveryAgreementsSelect<T extends boolean = true> {
  sender?:
    | T
    | {
        agreed?: T;
        agreedBy?: T;
        agreedAt?: T;
      };
  recipient?:
    | T
    | {
        agreed?: T;
        agreedBy?: T;
        agreedAt?: T;
      };
  bothAgreed?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConfirmedDelivery_select".
 */
export interface ConfirmedDeliverySelect<T extends boolean = true> {
  mode?: T;
  datetime?: T;
  address?: T;
  confirmedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}