import { NullableValidator } from '@lactalink/agents/payload';
import { extractID } from '@lactalink/utilities/extractors';
import { CollectionSlug, PolymorphicRelationshipField, SingleRelationshipField } from 'payload';

/**
 * Create a `User` relationship field with optional overrides.
 * Value is auto-set to the current user on create
 * therefore, validation is bypassed.
 * @param overrides `RelationshipField` overrides
 * @returns `RelationshipField`
 *
 * Default field configuration:
 * @defaultValue name='user'
 * @defaultValue type='relationship'
 * @defaultValue relationTo='users'
 * @defaultValue hasMany=false
 * @defaultValue admin.position='sidebar'
 * @defaultValue admin.readOnly=true
 * @defaultValue admin.description='The user who created this entry.
 * (Auto-generated by the current authenticated user, safe to ignore)'
 */
export function createUserField(
  overrides: Partial<SingleRelationshipField> = {}
): SingleRelationshipField {
  //@ts-expect-error - Payload types are not correctly inferring the polymorphic relationship
  return {
    name: 'user',
    type: 'relationship',
    relationTo: 'users',
    hasMany: false,
    validate: NullableValidator.relationship,
    hooks: {
      beforeChange: [
        ({ value, req, operation }) => {
          if (operation !== 'create' || !req.user) return value;

          // Preserve existing value if valid string
          if (value) return value;

          return extractID(req.user);
        },
      ],
    },

    ...overrides,

    admin: {
      readOnly: true,
      position: overrides.admin?.position === undefined ? undefined : 'sidebar',
      description:
        'The user who created this entry. (Auto-generated by the current authenticated user, safe to ignore)',
      ...overrides.admin,
    },
  };
}

/**
 * Create a `UserProfile` polymorphic-relationship field with optional overrides.
 * Value is auto-set to the current `UserProfile` on create
 * therefore, validation is bypassed.
 * @param overrides `RelationshipField` overrides
 * @returns `RelationshipField`
 *
 * Default field configuration:
 * @defaultValue name='user'
 * @defaultValue type='relationship'
 * @defaultValue relationTo=['individuals', 'milkBanks', 'hospitals']
 * @defaultValue hasMany=false
 * @defaultValue admin.position='sidebar'
 * @defaultValue admin.readOnly=true
 * @defaultValue admin.description='The profile of the user who created this entry.
 * (Auto-generated by the current authenticated user, safe to ignore)'
 */
export function createUserProfileField(
  overrides: Partial<PolymorphicRelationshipField> = {}
): PolymorphicRelationshipField {
  const profileRelations: CollectionSlug[] = ['individuals', 'milkBanks', 'hospitals'];

  //@ts-expect-error - Payload types are not correctly inferring the polymorphic relationship
  return {
    name: 'user',
    type: 'relationship',
    relationTo: profileRelations,
    hasMany: false,
    validate: NullableValidator.relationship,
    hooks: {
      beforeChange: [
        ({ value, req, operation }) => {
          if (operation !== 'create' || !req.user?.profile) return value;

          // Preserve existing value
          if (value) return value;

          return {
            relationTo: req.user.profile.relationTo,
            value: extractID(req.user.profile.value),
          };
        },
      ],
    },

    ...overrides,

    admin: {
      readOnly: true,
      position: overrides.admin?.position === undefined ? undefined : 'sidebar',
      description:
        'The profile of the user who created this entry. (Auto-generated by the current authenticated user, safe to ignore)',
      ...overrides.admin,
    },
  };
}
