import { NullableValidator } from '@lactalink/agents/payload';
import { extractID } from '@lactalink/utilities/extractors';
import isString from 'lodash/isString';
import { CollectionSlug, PolymorphicRelationshipField, SingleRelationshipField } from 'payload';

const profileRelations: CollectionSlug[] = ['individuals', 'milkBanks', 'hospitals'];

/**
 * Create a `User` relationship field with optional overrides.
 * Value is auto-set to the current user on create
 * therefore, validation is bypassed.
 * @param overrides `RelationshipField` overrides
 * @returns `RelationshipField`
 *
 * Default field configuration:
 * @defaultValue name='user'
 * @defaultValue type='relationship'
 * @defaultValue relationTo='users'
 * @defaultValue hasMany=false
 * @defaultValue admin.position='sidebar'
 * @defaultValue admin.readOnly=true
 * @defaultValue admin.description='The user who created this entry.
 * (Auto-generated by the current authenticated user, safe to ignore)'
 */
export function createUserField(
  overrides: Partial<SingleRelationshipField> = {}
): SingleRelationshipField {
  //@ts-expect-error - Payload types are not correctly inferring the polymorphic relationship
  return {
    name: 'user',
    type: 'relationship',
    relationTo: 'users',
    hasMany: false,
    validate: NullableValidator.relationship,
    hooks: {
      beforeChange: [
        ({ value, req, operation }) => {
          if (operation !== 'create' || !req.user) return value;

          // Preserve existing value if valid string
          if (isValidID(value)) return value;

          // Preserve existing value if valid relationship object
          if (isValidRelationshipObject(value)) {
            return value.id;
          }

          return extractID(req.user);
        },
      ],
    },

    ...overrides,

    admin: {
      readOnly: true,
      position: overrides.admin?.position === undefined ? undefined : 'sidebar',
      description:
        'The user who created this entry. (Auto-generated by the current authenticated user, safe to ignore)',
      ...overrides.admin,
    },
  };
}

/**
 * Create a `UserProfile` polymorphic-relationship field with optional overrides.
 * Value is auto-set to the current `UserProfile` on create
 * therefore, validation is bypassed.
 * @param overrides `RelationshipField` overrides
 * @returns `RelationshipField`
 *
 * Default field configuration:
 * @defaultValue name='user'
 * @defaultValue type='relationship'
 * @defaultValue relationTo=['individuals', 'milkBanks', 'hospitals']
 * @defaultValue hasMany=false
 * @defaultValue admin.position='sidebar'
 * @defaultValue admin.readOnly=true
 * @defaultValue admin.description='The profile of the user who created this entry.
 * (Auto-generated by the current authenticated user, safe to ignore)'
 */
export function createUserProfileField(
  overrides: Partial<PolymorphicRelationshipField> = {}
): PolymorphicRelationshipField {
  //@ts-expect-error - Payload types are not correctly inferring the polymorphic relationship
  return {
    name: 'user',
    type: 'relationship',
    relationTo: profileRelations,
    hasMany: false,
    validate: NullableValidator.relationship,
    hooks: {
      beforeChange: [
        ({ value, req, operation }) => {
          if (operation !== 'create' || !req.user?.profile) return value;

          // Preserve existing value if valid
          if (isValidPolymorphicRelationshipObject(value)) return value;

          return {
            relationTo: req.user.profile.relationTo,
            value: extractID(req.user.profile.value),
          };
        },
      ],
    },

    ...overrides,

    admin: {
      readOnly: true,
      position: overrides.admin?.position === undefined ? undefined : 'sidebar',
      description:
        'The profile of the user who created this entry. (Auto-generated by the current authenticated user, safe to ignore)',
      ...overrides.admin,
    },
  };
}

//#region Helpers/Validators ---------------------------------------------------------------------
function isValidID(value: unknown): value is string {
  return typeof value === 'string' && value.trim() !== '';
}

function isValidRelationshipObject(value: unknown): value is { id: string } {
  return typeof value === 'object' && value !== null && 'id' in value && isValidID(value.id);
}

function isValidPolymorphicRelationshipObject(
  value: unknown
): value is { value: string; relationTo: CollectionSlug } {
  return (
    typeof value === 'object' &&
    value !== null &&
    'value' in value &&
    (isValidID(value.value) || isValidRelationshipObject(value.value)) &&
    'relationTo' in value &&
    isString(value.relationTo) &&
    profileRelations.includes(value.relationTo as CollectionSlug)
  );
}
//#endregion
