import { postgresAdapter } from '@payloadcms/db-postgres';
import { resendAdapter } from '@payloadcms/email-resend';
import {
  AlignFeature,
  BoldFeature,
  FixedToolbarFeature,
  HeadingFeature,
  lexicalEditor,
  ParagraphFeature,
} from '@payloadcms/richtext-lexical';
import path from 'path';
import { buildConfig } from 'payload';
import sharp from 'sharp';
import { fileURLToPath } from 'url';
import Collections, { Users } from './collections';
import { Endpoints } from './endpoints';
import { jobs } from './jobs';
import { views } from './lib/db/drizzle/schema';
import { plugins } from './lib/plugins';
import { baseAdminMeta } from './lib/utils/baseMeta';
import { getServerSideURL } from './lib/utils/getURL';

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

export default buildConfig({
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
    components: {
      graphics: {
        Logo: '@/components/Logo',
        Icon: '@/components/HomeIcon',
      },
      beforeDashboard: ['@/components/admin/welcome-card'],
      providers: ['@/components/providers'],
    },
    avatar: 'default',
    suppressHydrationWarning: true,
    meta: baseAdminMeta,
  },
  serverURL: getServerSideURL(),
  collections: Collections,
  jobs: jobs,
  endpoints: Endpoints,
  sharp,
  plugins,
  maxDepth: 5,
  defaultDepth: 3,
  i18n: { translations: { en: { general: { payloadSettings: 'Settings' } } } },
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    // Output to @lactalink/types package
    outputFile: path.resolve(dirname, '../../../packages/types/src/payload-types/generated.ts'),
    autoGenerate: true,
    declare: false,
  },
  logger: {
    level: process.env.NODE_ENV === 'production' ? 'error' : 'info',
    options: {},
  },
  editor: lexicalEditor({
    features: ({ rootFeatures }) => {
      return [
        ...rootFeatures,
        FixedToolbarFeature(),
        HeadingFeature({ enabledHeadingSizes: ['h1', 'h2', 'h3', 'h4'] }),
        BoldFeature(),
        ParagraphFeature(),
        AlignFeature(),
      ];
    },
  }),
  email: resendAdapter({
    defaultFromAddress: 'no-reply@lactalink.com',
    defaultFromName: 'LactaLink',
    apiKey: process.env.RESEND_API_KEY || '',
  }),
  db: postgresAdapter({
    idType: 'uuid',
    allowIDOnCreate: true,
    generateSchemaOutputFile: path.resolve(dirname, './lib/db/drizzle/schema/payload-schema.ts'),
    pool: {
      connectionString: process.env.DATABASE_URI || '',
    },
    beforeSchemaInit: [
      ({ schema, adapter }) => {
        if (!adapter.rawTables.users) {
          console.warn('Users table not found in raw tables');
          return schema;
        }
        // Add a new column to generated by Payload table:
        adapter.rawTables.users.columns.authId = {
          name: 'auth_id',
          type: 'uuid',
          notNull: false,
        };

        return {
          ...schema,
          tables: {
            ...schema.tables,
            ...views,
          },
        };
      },
    ],
  }),
});
