import { postgresAdapter } from '@payloadcms/db-postgres';
import { uuid } from '@payloadcms/db-postgres/drizzle/pg-core';
import { lexicalEditor } from '@payloadcms/richtext-lexical';
import path from 'path';
import { buildConfig } from 'payload';
import sharp from 'sharp';
import { fileURLToPath } from 'url';
import Collections, { Users } from './collections';
import { Endpoints } from './endpoints';
import { plugins } from './lib/plugins';
import { baseAdminMeta } from './lib/utils/baseMeta';
import { getServerSideURL } from './lib/utils/getURL';

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

export default buildConfig({
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
    components: {
      graphics: {
        Logo: '@/components/Logo',
        Icon: '@/components/HomeIcon',
      },
      beforeDashboard: ['@/components/BeforeDashboard'],
      providers: ['@/components/providers'],
    },
    avatar: 'default',
    suppressHydrationWarning: true,
    meta: baseAdminMeta,
  },
  collections: Collections,
  serverURL: getServerSideURL(),
  editor: lexicalEditor(),
  endpoints: Endpoints,
  sharp,
  plugins,
  i18n: { translations: { en: { general: { payloadSettings: 'Settings' } } } },
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    outputFile: path.resolve(dirname, './lib/types/payload-types.ts'),
  },
  db: postgresAdapter({
    idType: 'uuid',
    allowIDOnCreate: true,
    generateSchemaOutputFile: path.resolve(dirname, './lib/db/drizzle-schema.ts'),
    pool: {
      connectionString: process.env.DATABASE_URI || '',
    },
    beforeSchemaInit: [
      ({ schema, adapter }) => {
        if (!adapter.rawTables.users) {
          console.warn('Users table not found in raw tables');
          return schema;
        }
        // Add a new column to generated by Payload table:
        adapter.rawTables.users.columns.authId = {
          name: 'auth_id',
          type: 'uuid',
          notNull: false,
        };
        return schema;
      },
    ],
    afterSchemaInit: [
      ({ schema, extendTable }) => {
        if (!schema.tables.users) {
          console.warn('Users table not found in schema');
          return schema;
        }
        extendTable({
          table: schema.tables.users,
          columns: {
            authId: uuid('auth_id').unique(),
          },
        });
        return schema;
      },
    ],
  }),
});
