import type { Donation, Request } from '@lactalink/types/payload-generated-types';
import { extractID } from '@lactalink/utilities/extractors';
import type { IApiClient } from '../../interfaces';

/**
 * Service for managing read tracking of donations and requests.
 * Handles marking items as read/seen by users.
 */
export class ReadTrackingService {
  /**
   * Creates a new ReadTrackingService instance.
   * @param apiClient - The API client used to communicate with the backend
   */
  constructor(private apiClient: IApiClient) {}

  /**
   * Marks a donation as read by a user
   * @param donation - The donation to mark as read
   * @returns The updated donation
   */
  async markDonationAsRead(donation: string | Donation): Promise<Donation | null> {
    // Check if already read
    const alreadyRead = await this.isDonationRead(donation);
    if (alreadyRead) return Promise.resolve(null);

    await this.apiClient.create({
      collection: 'donation-reads',
      data: {
        donation: extractID(donation),
        //@ts-expect-error Autogenerated value from the server side
        user: undefined,
      },
    });

    return this.apiClient.findByID({
      collection: 'donations',
      id: extractID(donation),
      depth: 3,
      joins: { reads: { count: true }, transactions: { count: true } },
    });
  }

  /**
   * Marks a request as read by a user
   * @param request - The request to mark as read
   * @returns The updated request
   */
  async markRequestAsRead(request: string | Request): Promise<Request | null> {
    // Check if already read
    const alreadyRead = await this.isRequestRead(request);
    if (alreadyRead) return Promise.resolve(null);

    await this.apiClient.create({
      collection: 'request-reads',
      data: {
        request: extractID(request),
        //@ts-expect-error Autogenerated value from the server side
        user: undefined,
      },
    });

    return this.apiClient.findByID({
      collection: 'requests',
      id: extractID(request),
      depth: 3,
      joins: { reads: { count: true }, transactions: { count: true } },
    });
  }

  /**
   * Checks if a donation has been read
   * @param donation - The donation to check
   * @returns `True` if the donation has been read
   */
  async isDonationRead(donation: string | Donation): Promise<boolean> {
    const { totalDocs } = await this.apiClient.count({
      collection: 'donation-reads',
      where: { donation: { equals: extractID(donation) } },
    });
    return totalDocs > 0;
  }

  /**
   * Checks if a request has been read
   * @param request - The request to check
   * @returns `True` if the request has been read
   */
  async isRequestRead(request: string | Request): Promise<boolean> {
    const { totalDocs } = await this.apiClient.count({
      collection: 'request-reads',
      where: { request: { equals: extractID(request) } },
    });
    return totalDocs > 0;
  }
}

export default ReadTrackingService;
