import gluestackPlugin from '@gluestack-ui/nativewind-utils/tailwind-plugin';

function withOpacity(colorVariable) {
  return `rgb(var(${colorVariable}) / <alpha-value>)`;
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'media',
  content: ['app/**/*.{tsx,jsx,ts,js}', 'components/**/*.{tsx,jsx,ts,js}'],
  presets: [require('nativewind/preset')],
  safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background|indicator)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark|primary)/,
    },
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          0: withOpacity('--color-primary-0'),
          50: withOpacity('--color-primary-50'),
          100: withOpacity('--color-primary-100'),
          200: withOpacity('--color-primary-200'),
          300: withOpacity('--color-primary-300'),
          400: withOpacity('--color-primary-400'),
          500: withOpacity('--color-primary-500'),
          600: withOpacity('--color-primary-600'),
          700: withOpacity('--color-primary-700'),
          800: withOpacity('--color-primary-800'),
          900: withOpacity('--color-primary-900'),
          950: withOpacity('--color-primary-950'),
        },
        secondary: {
          0: withOpacity('--color-secondary-0'),
          50: withOpacity('--color-secondary-50'),
          100: withOpacity('--color-secondary-100'),
          200: withOpacity('--color-secondary-200'),
          300: withOpacity('--color-secondary-300'),
          400: withOpacity('--color-secondary-400'),
          500: withOpacity('--color-secondary-500'),
          600: withOpacity('--color-secondary-600'),
          700: withOpacity('--color-secondary-700'),
          800: withOpacity('--color-secondary-800'),
          900: withOpacity('--color-secondary-900'),
          950: withOpacity('--color-secondary-950'),
        },
        tertiary: {
          0: withOpacity('--color-tertiary-0'),
          50: withOpacity('--color-tertiary-50'),
          100: withOpacity('--color-tertiary-100'),
          200: withOpacity('--color-tertiary-200'),
          300: withOpacity('--color-tertiary-300'),
          400: withOpacity('--color-tertiary-400'),
          500: withOpacity('--color-tertiary-500'),
          600: withOpacity('--color-tertiary-600'),
          700: withOpacity('--color-tertiary-700'),
          800: withOpacity('--color-tertiary-800'),
          900: withOpacity('--color-tertiary-900'),
          950: withOpacity('--color-tertiary-950'),
        },
        error: {
          0: withOpacity('--color-error-0'),
          50: withOpacity('--color-error-50'),
          100: withOpacity('--color-error-100'),
          200: withOpacity('--color-error-200'),
          300: withOpacity('--color-error-300'),
          400: withOpacity('--color-error-400'),
          500: withOpacity('--color-error-500'),
          600: withOpacity('--color-error-600'),
          700: withOpacity('--color-error-700'),
          800: withOpacity('--color-error-800'),
          900: withOpacity('--color-error-900'),
          950: withOpacity('--color-error-950'),
        },
        success: {
          0: withOpacity('--color-success-0'),
          50: withOpacity('--color-success-50'),
          100: withOpacity('--color-success-100'),
          200: withOpacity('--color-success-200'),
          300: withOpacity('--color-success-300'),
          400: withOpacity('--color-success-400'),
          500: withOpacity('--color-success-500'),
          600: withOpacity('--color-success-600'),
          700: withOpacity('--color-success-700'),
          800: withOpacity('--color-success-800'),
          900: withOpacity('--color-success-900'),
          950: withOpacity('--color-success-950'),
        },
        warning: {
          0: withOpacity('--color-warning-0'),
          50: withOpacity('--color-warning-50'),
          100: withOpacity('--color-warning-100'),
          200: withOpacity('--color-warning-200'),
          300: withOpacity('--color-warning-300'),
          400: withOpacity('--color-warning-400'),
          500: withOpacity('--color-warning-500'),
          600: withOpacity('--color-warning-600'),
          700: withOpacity('--color-warning-700'),
          800: withOpacity('--color-warning-800'),
          900: withOpacity('--color-warning-900'),
          950: withOpacity('--color-warning-950'),
        },
        info: {
          0: withOpacity('--color-info-0'),
          50: withOpacity('--color-info-50'),
          100: withOpacity('--color-info-100'),
          200: withOpacity('--color-info-200'),
          300: withOpacity('--color-info-300'),
          400: withOpacity('--color-info-400'),
          500: withOpacity('--color-info-500'),
          600: withOpacity('--color-info-600'),
          700: withOpacity('--color-info-700'),
          800: withOpacity('--color-info-800'),
          900: withOpacity('--color-info-900'),
          950: withOpacity('--color-info-950'),
        },
        typography: {
          0: withOpacity('--color-typography-0'),
          50: withOpacity('--color-typography-50'),
          100: withOpacity('--color-typography-100'),
          200: withOpacity('--color-typography-200'),
          300: withOpacity('--color-typography-300'),
          400: withOpacity('--color-typography-400'),
          500: withOpacity('--color-typography-500'),
          600: withOpacity('--color-typography-600'),
          700: withOpacity('--color-typography-700'),
          800: withOpacity('--color-typography-800'),
          900: withOpacity('--color-typography-900'),
          950: withOpacity('--color-typography-950'),
          white: 'rgb(255 255 255 / <alpha-value>)',
          gray: 'rgb(212 212 212 / <alpha-value>)',
          black: 'rgb(24 23 24 / <alpha-value>)',
        },
        outline: {
          0: withOpacity('--color-outline-0'),
          50: withOpacity('--color-outline-50'),
          100: withOpacity('--color-outline-100'),
          200: withOpacity('--color-outline-200'),
          300: withOpacity('--color-outline-300'),
          400: withOpacity('--color-outline-400'),
          500: withOpacity('--color-outline-500'),
          600: withOpacity('--color-outline-600'),
          700: withOpacity('--color-outline-700'),
          800: withOpacity('--color-outline-800'),
          900: withOpacity('--color-outline-900'),
          950: withOpacity('--color-outline-950'),
        },
        background: {
          0: withOpacity('--color-background-0'),
          50: withOpacity('--color-background-50'),
          100: withOpacity('--color-background-100'),
          200: withOpacity('--color-background-200'),
          300: withOpacity('--color-background-300'),
          400: withOpacity('--color-background-400'),
          500: withOpacity('--color-background-500'),
          600: withOpacity('--color-background-600'),
          700: withOpacity('--color-background-700'),
          800: withOpacity('--color-background-800'),
          900: withOpacity('--color-background-900'),
          950: withOpacity('--color-background-950'),
          error: withOpacity('--color-background-error'),
          warning: withOpacity('--color-background-warning'),
          muted: withOpacity('--color-background-muted'),
          success: withOpacity('--color-background-success'),
          info: withOpacity('--color-background-info'),
          light: 'rgb(255 244 245 / <alpha-value>)',
          dark: 'rgb(51 46 46 / <alpha-value>)',
        },
        indicator: {
          primary: withOpacity('--color-indicator-primary'),
          info: withOpacity('--color-indicator-info'),
          error: withOpacity('--color-indicator-error'),
          ripple: withOpacity('--color-indicator-ripple'),
        },
      },
      fontFamily: {
        mono: 'var(--font-mono)',
        heading: ['Jakarta-Bold', 'sans-serif'],
        body: ['Jakarta-Regular', 'sans-serif'],
        sans: ['Jakarta-Regular', 'sans-serif'],
        JakartaBold: ['Jakarta-Bold', 'sans-serif'],
        JakartaExtraBold: ['Jakarta-ExtraBold', 'sans-serif'],
        JakartaExtraLight: ['Jakarta-ExtraLight', 'sans-serif'],
        JakartaLight: ['Jakarta-Light', 'sans-serif'],
        JakartaMedium: ['Jakarta-Medium', 'sans-serif'],
        JakartaSemiBold: ['Jakarta-SemiBold', 'sans-serif'],
        JakartaItalic: ['Jakarta-Italic', 'sans-serif'],
      },
      fontWeight: {
        extrablack: '950',
      },
      fontSize: {
        '2xs': '10px',
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
    },
  },
  plugins: [gluestackPlugin],
};
