/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  uuid,
  varchar,
  timestamp,
  numeric,
  boolean,
  serial,
  integer,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core';
import { sql, relations } from '@payloadcms/db-postgres/drizzle';
export const enum_cities_municipalities_type = pgEnum('enum_cities_municipalities_type', [
  'NONE',
  'CITY',
  'MUNICIPALITY',
]);
export const enum_hospitals_type = pgEnum('enum_hospitals_type', [
  'GOVERNMENT',
  'PRIVATE',
  'OTHER',
]);
export const enum_individuals_gender = pgEnum('enum_individuals_gender', [
  'MALE',
  'FEMALE',
  'OTHER',
]);
export const enum_individuals_marital_status = pgEnum('enum_individuals_marital_status', [
  'SINGLE',
  'MARRIED',
  'WIDOWED',
  'DIVORCED',
  'SEPARATED',
  'N/A',
]);
export const enum_milk_banks_type = pgEnum('enum_milk_banks_type', [
  'GOVERNMENT',
  'PRIVATE',
  'OTHER',
]);
export const enum_users_role = pgEnum('enum_users_role', ['AUTHENTICATED', 'ADMIN']);
export const enum_users_profile_type = pgEnum('enum_users_profile_type', [
  'INDIVIDUAL',
  'HOSPITAL',
  'MILK_BANK',
]);

export const addresses = pgTable(
  'addresses',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    street: varchar('street'),
    region: uuid('region_id')
      .notNull()
      .references(() => regions.id, {
        onDelete: 'set null',
      }),
    province: uuid('province_id')
      .notNull()
      .references(() => provinces.id, {
        onDelete: 'set null',
      }),
    cityMunicipality: uuid('city_municipality_id')
      .notNull()
      .references(() => cities_municipalities.id, {
        onDelete: 'set null',
      }),
    barangay: uuid('barangay_id')
      .notNull()
      .references(() => barangays.id, {
        onDelete: 'set null',
      }),
    islandGroup: uuid('island_group_id').references(() => island_groups.id, {
      onDelete: 'set null',
    }),
    displayName: varchar('display_name'),
    owner: uuid('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    addresses_region_idx: index('addresses_region_idx').on(columns.region),
    addresses_province_idx: index('addresses_province_idx').on(columns.province),
    addresses_city_municipality_idx: index('addresses_city_municipality_idx').on(
      columns.cityMunicipality
    ),
    addresses_barangay_idx: index('addresses_barangay_idx').on(columns.barangay),
    addresses_island_group_idx: index('addresses_island_group_idx').on(columns.islandGroup),
    addresses_owner_idx: index('addresses_owner_idx').on(columns.owner),
    addresses_updated_at_idx: index('addresses_updated_at_idx').on(columns.updatedAt),
    addresses_created_at_idx: index('addresses_created_at_idx').on(columns.createdAt),
  })
);

export const avatars = pgTable(
  'avatars',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    alt: varchar('alt'),
    owner: uuid('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width'),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height'),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize'),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_icon_url: varchar('sizes_icon_url'),
    sizes_icon_width: numeric('sizes_icon_width'),
    sizes_icon_height: numeric('sizes_icon_height'),
    sizes_icon_mimeType: varchar('sizes_icon_mime_type'),
    sizes_icon_filesize: numeric('sizes_icon_filesize'),
    sizes_icon_filename: varchar('sizes_icon_filename'),
  },
  (columns) => ({
    avatars_owner_idx: index('avatars_owner_idx').on(columns.owner),
    avatars_updated_at_idx: index('avatars_updated_at_idx').on(columns.updatedAt),
    avatars_created_at_idx: index('avatars_created_at_idx').on(columns.createdAt),
    avatars_filename_idx: uniqueIndex('avatars_filename_idx').on(columns.filename),
    avatars_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      'avatars_sizes_thumbnail_sizes_thumbnail_filename_idx'
    ).on(columns.sizes_thumbnail_filename),
    avatars_sizes_icon_sizes_icon_filename_idx: index(
      'avatars_sizes_icon_sizes_icon_filename_idx'
    ).on(columns.sizes_icon_filename),
  })
);

export const barangays = pgTable(
  'barangays',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    oldName: varchar('old_name'),
    code: varchar('code').notNull(),
    subMunicipalityCode: varchar('sub_municipality_code'),
    districtCode: varchar('district_code'),
    cityMunicipality: uuid('city_municipality_id')
      .notNull()
      .references(() => cities_municipalities.id, {
        onDelete: 'set null',
      }),
    province: uuid('province_id').references(() => provinces.id, {
      onDelete: 'set null',
    }),
    region: uuid('region_id')
      .notNull()
      .references(() => regions.id, {
        onDelete: 'set null',
      }),
    islandGroup: uuid('island_group_id')
      .notNull()
      .references(() => island_groups.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    barangays_code_idx: uniqueIndex('barangays_code_idx').on(columns.code),
    barangays_city_municipality_idx: index('barangays_city_municipality_idx').on(
      columns.cityMunicipality
    ),
    barangays_province_idx: index('barangays_province_idx').on(columns.province),
    barangays_region_idx: index('barangays_region_idx').on(columns.region),
    barangays_island_group_idx: index('barangays_island_group_idx').on(columns.islandGroup),
    barangays_updated_at_idx: index('barangays_updated_at_idx').on(columns.updatedAt),
    barangays_created_at_idx: index('barangays_created_at_idx').on(columns.createdAt),
  })
);

export const cities_municipalities = pgTable(
  'cities_municipalities',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    oldName: varchar('old_name'),
    isCapital: boolean('is_capital').notNull().default(false),
    code: varchar('code').notNull(),
    type: enum_cities_municipalities_type('type').notNull().default('NONE'),
    districtCode: varchar('district_code'),
    province: uuid('province_id').references(() => provinces.id, {
      onDelete: 'set null',
    }),
    region: uuid('region_id')
      .notNull()
      .references(() => regions.id, {
        onDelete: 'set null',
      }),
    islandGroup: uuid('island_group_id')
      .notNull()
      .references(() => island_groups.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    cities_municipalities_code_idx: uniqueIndex('cities_municipalities_code_idx').on(columns.code),
    cities_municipalities_province_idx: index('cities_municipalities_province_idx').on(
      columns.province
    ),
    cities_municipalities_region_idx: index('cities_municipalities_region_idx').on(columns.region),
    cities_municipalities_island_group_idx: index('cities_municipalities_island_group_idx').on(
      columns.islandGroup
    ),
    cities_municipalities_updated_at_idx: index('cities_municipalities_updated_at_idx').on(
      columns.updatedAt
    ),
    cities_municipalities_created_at_idx: index('cities_municipalities_created_at_idx').on(
      columns.createdAt
    ),
  })
);

export const hospitals = pgTable(
  'hospitals',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    owner: uuid('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    avatar: uuid('avatar_id').references(() => avatars.id, {
      onDelete: 'set null',
    }),
    name: varchar('name').notNull(),
    description: varchar('description'),
    head: varchar('head'),
    hospitalID: varchar('hospital_i_d'),
    type: enum_hospitals_type('type'),
    phone: varchar('phone'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    hospitals_owner_idx: index('hospitals_owner_idx').on(columns.owner),
    hospitals_avatar_idx: index('hospitals_avatar_idx').on(columns.avatar),
    hospitals_phone_idx: uniqueIndex('hospitals_phone_idx').on(columns.phone),
    hospitals_updated_at_idx: index('hospitals_updated_at_idx').on(columns.updatedAt),
    hospitals_created_at_idx: index('hospitals_created_at_idx').on(columns.createdAt),
  })
);

export const hospitals_rels = pgTable(
  'hospitals_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    addressesID: uuid('addresses_id'),
  },
  (columns) => ({
    order: index('hospitals_rels_order_idx').on(columns.order),
    parentIdx: index('hospitals_rels_parent_idx').on(columns.parent),
    pathIdx: index('hospitals_rels_path_idx').on(columns.path),
    hospitals_rels_addresses_id_idx: index('hospitals_rels_addresses_id_idx').on(
      columns.addressesID
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [hospitals.id],
      name: 'hospitals_rels_parent_fk',
    }).onDelete('cascade'),
    addressesIdFk: foreignKey({
      columns: [columns['addressesID']],
      foreignColumns: [addresses.id],
      name: 'hospitals_rels_addresses_fk',
    }).onDelete('cascade'),
  })
);

export const images = pgTable(
  'images',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    alt: varchar('alt'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width'),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height'),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize'),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_square_url: varchar('sizes_square_url'),
    sizes_square_width: numeric('sizes_square_width'),
    sizes_square_height: numeric('sizes_square_height'),
    sizes_square_mimeType: varchar('sizes_square_mime_type'),
    sizes_square_filesize: numeric('sizes_square_filesize'),
    sizes_square_filename: varchar('sizes_square_filename'),
    sizes_small_url: varchar('sizes_small_url'),
    sizes_small_width: numeric('sizes_small_width'),
    sizes_small_height: numeric('sizes_small_height'),
    sizes_small_mimeType: varchar('sizes_small_mime_type'),
    sizes_small_filesize: numeric('sizes_small_filesize'),
    sizes_small_filename: varchar('sizes_small_filename'),
    sizes_medium_url: varchar('sizes_medium_url'),
    sizes_medium_width: numeric('sizes_medium_width'),
    sizes_medium_height: numeric('sizes_medium_height'),
    sizes_medium_mimeType: varchar('sizes_medium_mime_type'),
    sizes_medium_filesize: numeric('sizes_medium_filesize'),
    sizes_medium_filename: varchar('sizes_medium_filename'),
    sizes_large_url: varchar('sizes_large_url'),
    sizes_large_width: numeric('sizes_large_width'),
    sizes_large_height: numeric('sizes_large_height'),
    sizes_large_mimeType: varchar('sizes_large_mime_type'),
    sizes_large_filesize: numeric('sizes_large_filesize'),
    sizes_large_filename: varchar('sizes_large_filename'),
    sizes_xlarge_url: varchar('sizes_xlarge_url'),
    sizes_xlarge_width: numeric('sizes_xlarge_width'),
    sizes_xlarge_height: numeric('sizes_xlarge_height'),
    sizes_xlarge_mimeType: varchar('sizes_xlarge_mime_type'),
    sizes_xlarge_filesize: numeric('sizes_xlarge_filesize'),
    sizes_xlarge_filename: varchar('sizes_xlarge_filename'),
    sizes_og_url: varchar('sizes_og_url'),
    sizes_og_width: numeric('sizes_og_width'),
    sizes_og_height: numeric('sizes_og_height'),
    sizes_og_mimeType: varchar('sizes_og_mime_type'),
    sizes_og_filesize: numeric('sizes_og_filesize'),
    sizes_og_filename: varchar('sizes_og_filename'),
  },
  (columns) => ({
    images_updated_at_idx: index('images_updated_at_idx').on(columns.updatedAt),
    images_created_at_idx: index('images_created_at_idx').on(columns.createdAt),
    images_filename_idx: uniqueIndex('images_filename_idx').on(columns.filename),
    images_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      'images_sizes_thumbnail_sizes_thumbnail_filename_idx'
    ).on(columns.sizes_thumbnail_filename),
    images_sizes_square_sizes_square_filename_idx: index(
      'images_sizes_square_sizes_square_filename_idx'
    ).on(columns.sizes_square_filename),
    images_sizes_small_sizes_small_filename_idx: index(
      'images_sizes_small_sizes_small_filename_idx'
    ).on(columns.sizes_small_filename),
    images_sizes_medium_sizes_medium_filename_idx: index(
      'images_sizes_medium_sizes_medium_filename_idx'
    ).on(columns.sizes_medium_filename),
    images_sizes_large_sizes_large_filename_idx: index(
      'images_sizes_large_sizes_large_filename_idx'
    ).on(columns.sizes_large_filename),
    images_sizes_xlarge_sizes_xlarge_filename_idx: index(
      'images_sizes_xlarge_sizes_xlarge_filename_idx'
    ).on(columns.sizes_xlarge_filename),
    images_sizes_og_sizes_og_filename_idx: index('images_sizes_og_sizes_og_filename_idx').on(
      columns.sizes_og_filename
    ),
  })
);

export const images_rels = pgTable(
  'images_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
  },
  (columns) => ({
    order: index('images_rels_order_idx').on(columns.order),
    parentIdx: index('images_rels_parent_idx').on(columns.parent),
    pathIdx: index('images_rels_path_idx').on(columns.path),
    images_rels_users_id_idx: index('images_rels_users_id_idx').on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [images.id],
      name: 'images_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'images_rels_users_fk',
    }).onDelete('cascade'),
  })
);

export const individuals = pgTable(
  'individuals',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    displayName: varchar('display_name'),
    owner: uuid('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    avatar: uuid('avatar_id').references(() => avatars.id, {
      onDelete: 'set null',
    }),
    givenName: varchar('given_name').notNull(),
    middleName: varchar('middle_name'),
    familyName: varchar('family_name').notNull(),
    birth: timestamp('birth', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    phone: varchar('phone'),
    dependents: numeric('dependents'),
    gender: enum_individuals_gender('gender').notNull(),
    maritalStatus: enum_individuals_marital_status('marital_status').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    individuals_owner_idx: index('individuals_owner_idx').on(columns.owner),
    individuals_avatar_idx: index('individuals_avatar_idx').on(columns.avatar),
    individuals_phone_idx: uniqueIndex('individuals_phone_idx').on(columns.phone),
    individuals_updated_at_idx: index('individuals_updated_at_idx').on(columns.updatedAt),
    individuals_created_at_idx: index('individuals_created_at_idx').on(columns.createdAt),
  })
);

export const individuals_rels = pgTable(
  'individuals_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    addressesID: uuid('addresses_id'),
  },
  (columns) => ({
    order: index('individuals_rels_order_idx').on(columns.order),
    parentIdx: index('individuals_rels_parent_idx').on(columns.parent),
    pathIdx: index('individuals_rels_path_idx').on(columns.path),
    individuals_rels_addresses_id_idx: index('individuals_rels_addresses_id_idx').on(
      columns.addressesID
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [individuals.id],
      name: 'individuals_rels_parent_fk',
    }).onDelete('cascade'),
    addressesIdFk: foreignKey({
      columns: [columns['addressesID']],
      foreignColumns: [addresses.id],
      name: 'individuals_rels_addresses_fk',
    }).onDelete('cascade'),
  })
);

export const island_groups = pgTable(
  'island_groups',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    code: varchar('code').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    island_groups_code_idx: uniqueIndex('island_groups_code_idx').on(columns.code),
    island_groups_updated_at_idx: index('island_groups_updated_at_idx').on(columns.updatedAt),
    island_groups_created_at_idx: index('island_groups_created_at_idx').on(columns.createdAt),
  })
);

export const milk_banks = pgTable(
  'milk_banks',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    owner: uuid('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    avatar: uuid('avatar_id').references(() => avatars.id, {
      onDelete: 'set null',
    }),
    name: varchar('name').notNull(),
    description: varchar('description'),
    head: varchar('head'),
    type: enum_milk_banks_type('type'),
    phone: varchar('phone'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    milk_banks_owner_idx: index('milk_banks_owner_idx').on(columns.owner),
    milk_banks_avatar_idx: index('milk_banks_avatar_idx').on(columns.avatar),
    milk_banks_phone_idx: uniqueIndex('milk_banks_phone_idx').on(columns.phone),
    milk_banks_updated_at_idx: index('milk_banks_updated_at_idx').on(columns.updatedAt),
    milk_banks_created_at_idx: index('milk_banks_created_at_idx').on(columns.createdAt),
  })
);

export const milk_banks_rels = pgTable(
  'milk_banks_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    addressesID: uuid('addresses_id'),
  },
  (columns) => ({
    order: index('milk_banks_rels_order_idx').on(columns.order),
    parentIdx: index('milk_banks_rels_parent_idx').on(columns.parent),
    pathIdx: index('milk_banks_rels_path_idx').on(columns.path),
    milk_banks_rels_addresses_id_idx: index('milk_banks_rels_addresses_id_idx').on(
      columns.addressesID
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [milk_banks.id],
      name: 'milk_banks_rels_parent_fk',
    }).onDelete('cascade'),
    addressesIdFk: foreignKey({
      columns: [columns['addressesID']],
      foreignColumns: [addresses.id],
      name: 'milk_banks_rels_addresses_fk',
    }).onDelete('cascade'),
  })
);

export const provinces = pgTable(
  'provinces',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    code: varchar('code').notNull(),
    region: uuid('region_id')
      .notNull()
      .references(() => regions.id, {
        onDelete: 'set null',
      }),
    islandGroup: uuid('island_group_id')
      .notNull()
      .references(() => island_groups.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    provinces_code_idx: uniqueIndex('provinces_code_idx').on(columns.code),
    provinces_region_idx: index('provinces_region_idx').on(columns.region),
    provinces_island_group_idx: index('provinces_island_group_idx').on(columns.islandGroup),
    provinces_updated_at_idx: index('provinces_updated_at_idx').on(columns.updatedAt),
    provinces_created_at_idx: index('provinces_created_at_idx').on(columns.createdAt),
  })
);

export const regions = pgTable(
  'regions',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    code: varchar('code').notNull(),
    regionName: varchar('region_name'),
    islandGroup: uuid('island_group_id')
      .notNull()
      .references(() => island_groups.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    regions_code_idx: uniqueIndex('regions_code_idx').on(columns.code),
    regions_island_group_idx: index('regions_island_group_idx').on(columns.islandGroup),
    regions_updated_at_idx: index('regions_updated_at_idx').on(columns.updatedAt),
    regions_created_at_idx: index('regions_created_at_idx').on(columns.createdAt),
  })
);

export const users = pgTable(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    email: varchar('email').notNull(),
    role: enum_users_role('role').default('AUTHENTICATED'),
    phone: varchar('phone'),
    profileType: enum_users_profile_type('profile_type').default('INDIVIDUAL'),
    lastSignInAt: timestamp('last_sign_in_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    emailConfirmedAt: timestamp('email_confirmed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    phoneConfirmedAt: timestamp('phone_confirmed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    authId: uuid('auth_id'),
  },
  (columns) => ({
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
    users_phone_idx: uniqueIndex('users_phone_idx').on(columns.phone),
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
  })
);

export const users_rels = pgTable(
  'users_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    individualsID: uuid('individuals_id'),
    milkBanksID: uuid('milk_banks_id'),
    hospitalsID: uuid('hospitals_id'),
  },
  (columns) => ({
    order: index('users_rels_order_idx').on(columns.order),
    parentIdx: index('users_rels_parent_idx').on(columns.parent),
    pathIdx: index('users_rels_path_idx').on(columns.path),
    users_rels_individuals_id_idx: index('users_rels_individuals_id_idx').on(columns.individualsID),
    users_rels_milk_banks_id_idx: index('users_rels_milk_banks_id_idx').on(columns.milkBanksID),
    users_rels_hospitals_id_idx: index('users_rels_hospitals_id_idx').on(columns.hospitalsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_rels_parent_fk',
    }).onDelete('cascade'),
    individualsIdFk: foreignKey({
      columns: [columns['individualsID']],
      foreignColumns: [individuals.id],
      name: 'users_rels_individuals_fk',
    }).onDelete('cascade'),
    milkBanksIdFk: foreignKey({
      columns: [columns['milkBanksID']],
      foreignColumns: [milk_banks.id],
      name: 'users_rels_milk_banks_fk',
    }).onDelete('cascade'),
    hospitalsIdFk: foreignKey({
      columns: [columns['hospitalsID']],
      foreignColumns: [hospitals.id],
      name: 'users_rels_hospitals_fk',
    }).onDelete('cascade'),
  })
);

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt
    ),
  })
);

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    addressesID: uuid('addresses_id'),
    avatarsID: uuid('avatars_id'),
    barangaysID: uuid('barangays_id'),
    citiesMunicipalitiesID: uuid('cities_municipalities_id'),
    hospitalsID: uuid('hospitals_id'),
    imagesID: uuid('images_id'),
    individualsID: uuid('individuals_id'),
    islandGroupsID: uuid('island_groups_id'),
    milkBanksID: uuid('milk_banks_id'),
    provincesID: uuid('provinces_id'),
    regionsID: uuid('regions_id'),
    usersID: uuid('users_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_addresses_id_idx: index(
      'payload_locked_documents_rels_addresses_id_idx'
    ).on(columns.addressesID),
    payload_locked_documents_rels_avatars_id_idx: index(
      'payload_locked_documents_rels_avatars_id_idx'
    ).on(columns.avatarsID),
    payload_locked_documents_rels_barangays_id_idx: index(
      'payload_locked_documents_rels_barangays_id_idx'
    ).on(columns.barangaysID),
    payload_locked_documents_rels_cities_municipalities_id_idx: index(
      'payload_locked_documents_rels_cities_municipalities_id_idx'
    ).on(columns.citiesMunicipalitiesID),
    payload_locked_documents_rels_hospitals_id_idx: index(
      'payload_locked_documents_rels_hospitals_id_idx'
    ).on(columns.hospitalsID),
    payload_locked_documents_rels_images_id_idx: index(
      'payload_locked_documents_rels_images_id_idx'
    ).on(columns.imagesID),
    payload_locked_documents_rels_individuals_id_idx: index(
      'payload_locked_documents_rels_individuals_id_idx'
    ).on(columns.individualsID),
    payload_locked_documents_rels_island_groups_id_idx: index(
      'payload_locked_documents_rels_island_groups_id_idx'
    ).on(columns.islandGroupsID),
    payload_locked_documents_rels_milk_banks_id_idx: index(
      'payload_locked_documents_rels_milk_banks_id_idx'
    ).on(columns.milkBanksID),
    payload_locked_documents_rels_provinces_id_idx: index(
      'payload_locked_documents_rels_provinces_id_idx'
    ).on(columns.provincesID),
    payload_locked_documents_rels_regions_id_idx: index(
      'payload_locked_documents_rels_regions_id_idx'
    ).on(columns.regionsID),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx'
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    addressesIdFk: foreignKey({
      columns: [columns['addressesID']],
      foreignColumns: [addresses.id],
      name: 'payload_locked_documents_rels_addresses_fk',
    }).onDelete('cascade'),
    avatarsIdFk: foreignKey({
      columns: [columns['avatarsID']],
      foreignColumns: [avatars.id],
      name: 'payload_locked_documents_rels_avatars_fk',
    }).onDelete('cascade'),
    barangaysIdFk: foreignKey({
      columns: [columns['barangaysID']],
      foreignColumns: [barangays.id],
      name: 'payload_locked_documents_rels_barangays_fk',
    }).onDelete('cascade'),
    citiesMunicipalitiesIdFk: foreignKey({
      columns: [columns['citiesMunicipalitiesID']],
      foreignColumns: [cities_municipalities.id],
      name: 'payload_locked_documents_rels_cities_municipalities_fk',
    }).onDelete('cascade'),
    hospitalsIdFk: foreignKey({
      columns: [columns['hospitalsID']],
      foreignColumns: [hospitals.id],
      name: 'payload_locked_documents_rels_hospitals_fk',
    }).onDelete('cascade'),
    imagesIdFk: foreignKey({
      columns: [columns['imagesID']],
      foreignColumns: [images.id],
      name: 'payload_locked_documents_rels_images_fk',
    }).onDelete('cascade'),
    individualsIdFk: foreignKey({
      columns: [columns['individualsID']],
      foreignColumns: [individuals.id],
      name: 'payload_locked_documents_rels_individuals_fk',
    }).onDelete('cascade'),
    islandGroupsIdFk: foreignKey({
      columns: [columns['islandGroupsID']],
      foreignColumns: [island_groups.id],
      name: 'payload_locked_documents_rels_island_groups_fk',
    }).onDelete('cascade'),
    milkBanksIdFk: foreignKey({
      columns: [columns['milkBanksID']],
      foreignColumns: [milk_banks.id],
      name: 'payload_locked_documents_rels_milk_banks_fk',
    }).onDelete('cascade'),
    provincesIdFk: foreignKey({
      columns: [columns['provincesID']],
      foreignColumns: [provinces.id],
      name: 'payload_locked_documents_rels_provinces_fk',
    }).onDelete('cascade'),
    regionsIdFk: foreignKey({
      columns: [columns['regionsID']],
      foreignColumns: [regions.id],
      name: 'payload_locked_documents_rels_regions_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
  })
);

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt
    ),
  })
);

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  })
);

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt
    ),
  })
);

export const relations_addresses = relations(addresses, ({ one }) => ({
  region: one(regions, {
    fields: [addresses.region],
    references: [regions.id],
    relationName: 'region',
  }),
  province: one(provinces, {
    fields: [addresses.province],
    references: [provinces.id],
    relationName: 'province',
  }),
  cityMunicipality: one(cities_municipalities, {
    fields: [addresses.cityMunicipality],
    references: [cities_municipalities.id],
    relationName: 'cityMunicipality',
  }),
  barangay: one(barangays, {
    fields: [addresses.barangay],
    references: [barangays.id],
    relationName: 'barangay',
  }),
  islandGroup: one(island_groups, {
    fields: [addresses.islandGroup],
    references: [island_groups.id],
    relationName: 'islandGroup',
  }),
  owner: one(users, {
    fields: [addresses.owner],
    references: [users.id],
    relationName: 'owner',
  }),
}));
export const relations_avatars = relations(avatars, ({ one }) => ({
  owner: one(users, {
    fields: [avatars.owner],
    references: [users.id],
    relationName: 'owner',
  }),
}));
export const relations_barangays = relations(barangays, ({ one }) => ({
  cityMunicipality: one(cities_municipalities, {
    fields: [barangays.cityMunicipality],
    references: [cities_municipalities.id],
    relationName: 'cityMunicipality',
  }),
  province: one(provinces, {
    fields: [barangays.province],
    references: [provinces.id],
    relationName: 'province',
  }),
  region: one(regions, {
    fields: [barangays.region],
    references: [regions.id],
    relationName: 'region',
  }),
  islandGroup: one(island_groups, {
    fields: [barangays.islandGroup],
    references: [island_groups.id],
    relationName: 'islandGroup',
  }),
}));
export const relations_cities_municipalities = relations(cities_municipalities, ({ one }) => ({
  province: one(provinces, {
    fields: [cities_municipalities.province],
    references: [provinces.id],
    relationName: 'province',
  }),
  region: one(regions, {
    fields: [cities_municipalities.region],
    references: [regions.id],
    relationName: 'region',
  }),
  islandGroup: one(island_groups, {
    fields: [cities_municipalities.islandGroup],
    references: [island_groups.id],
    relationName: 'islandGroup',
  }),
}));
export const relations_hospitals_rels = relations(hospitals_rels, ({ one }) => ({
  parent: one(hospitals, {
    fields: [hospitals_rels.parent],
    references: [hospitals.id],
    relationName: '_rels',
  }),
  addressesID: one(addresses, {
    fields: [hospitals_rels.addressesID],
    references: [addresses.id],
    relationName: 'addresses',
  }),
}));
export const relations_hospitals = relations(hospitals, ({ one, many }) => ({
  owner: one(users, {
    fields: [hospitals.owner],
    references: [users.id],
    relationName: 'owner',
  }),
  avatar: one(avatars, {
    fields: [hospitals.avatar],
    references: [avatars.id],
    relationName: 'avatar',
  }),
  _rels: many(hospitals_rels, {
    relationName: '_rels',
  }),
}));
export const relations_images_rels = relations(images_rels, ({ one }) => ({
  parent: one(images, {
    fields: [images_rels.parent],
    references: [images.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [images_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}));
export const relations_images = relations(images, ({ many }) => ({
  _rels: many(images_rels, {
    relationName: '_rels',
  }),
}));
export const relations_individuals_rels = relations(individuals_rels, ({ one }) => ({
  parent: one(individuals, {
    fields: [individuals_rels.parent],
    references: [individuals.id],
    relationName: '_rels',
  }),
  addressesID: one(addresses, {
    fields: [individuals_rels.addressesID],
    references: [addresses.id],
    relationName: 'addresses',
  }),
}));
export const relations_individuals = relations(individuals, ({ one, many }) => ({
  owner: one(users, {
    fields: [individuals.owner],
    references: [users.id],
    relationName: 'owner',
  }),
  avatar: one(avatars, {
    fields: [individuals.avatar],
    references: [avatars.id],
    relationName: 'avatar',
  }),
  _rels: many(individuals_rels, {
    relationName: '_rels',
  }),
}));
export const relations_island_groups = relations(island_groups, () => ({}));
export const relations_milk_banks_rels = relations(milk_banks_rels, ({ one }) => ({
  parent: one(milk_banks, {
    fields: [milk_banks_rels.parent],
    references: [milk_banks.id],
    relationName: '_rels',
  }),
  addressesID: one(addresses, {
    fields: [milk_banks_rels.addressesID],
    references: [addresses.id],
    relationName: 'addresses',
  }),
}));
export const relations_milk_banks = relations(milk_banks, ({ one, many }) => ({
  owner: one(users, {
    fields: [milk_banks.owner],
    references: [users.id],
    relationName: 'owner',
  }),
  avatar: one(avatars, {
    fields: [milk_banks.avatar],
    references: [avatars.id],
    relationName: 'avatar',
  }),
  _rels: many(milk_banks_rels, {
    relationName: '_rels',
  }),
}));
export const relations_provinces = relations(provinces, ({ one }) => ({
  region: one(regions, {
    fields: [provinces.region],
    references: [regions.id],
    relationName: 'region',
  }),
  islandGroup: one(island_groups, {
    fields: [provinces.islandGroup],
    references: [island_groups.id],
    relationName: 'islandGroup',
  }),
}));
export const relations_regions = relations(regions, ({ one }) => ({
  islandGroup: one(island_groups, {
    fields: [regions.islandGroup],
    references: [island_groups.id],
    relationName: 'islandGroup',
  }),
}));
export const relations_users_rels = relations(users_rels, ({ one }) => ({
  parent: one(users, {
    fields: [users_rels.parent],
    references: [users.id],
    relationName: '_rels',
  }),
  individualsID: one(individuals, {
    fields: [users_rels.individualsID],
    references: [individuals.id],
    relationName: 'individuals',
  }),
  milkBanksID: one(milk_banks, {
    fields: [users_rels.milkBanksID],
    references: [milk_banks.id],
    relationName: 'milkBanks',
  }),
  hospitalsID: one(hospitals, {
    fields: [users_rels.hospitalsID],
    references: [hospitals.id],
    relationName: 'hospitals',
  }),
}));
export const relations_users = relations(users, ({ many }) => ({
  _rels: many(users_rels, {
    relationName: '_rels',
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    addressesID: one(addresses, {
      fields: [payload_locked_documents_rels.addressesID],
      references: [addresses.id],
      relationName: 'addresses',
    }),
    avatarsID: one(avatars, {
      fields: [payload_locked_documents_rels.avatarsID],
      references: [avatars.id],
      relationName: 'avatars',
    }),
    barangaysID: one(barangays, {
      fields: [payload_locked_documents_rels.barangaysID],
      references: [barangays.id],
      relationName: 'barangays',
    }),
    citiesMunicipalitiesID: one(cities_municipalities, {
      fields: [payload_locked_documents_rels.citiesMunicipalitiesID],
      references: [cities_municipalities.id],
      relationName: 'citiesMunicipalities',
    }),
    hospitalsID: one(hospitals, {
      fields: [payload_locked_documents_rels.hospitalsID],
      references: [hospitals.id],
      relationName: 'hospitals',
    }),
    imagesID: one(images, {
      fields: [payload_locked_documents_rels.imagesID],
      references: [images.id],
      relationName: 'images',
    }),
    individualsID: one(individuals, {
      fields: [payload_locked_documents_rels.individualsID],
      references: [individuals.id],
      relationName: 'individuals',
    }),
    islandGroupsID: one(island_groups, {
      fields: [payload_locked_documents_rels.islandGroupsID],
      references: [island_groups.id],
      relationName: 'islandGroups',
    }),
    milkBanksID: one(milk_banks, {
      fields: [payload_locked_documents_rels.milkBanksID],
      references: [milk_banks.id],
      relationName: 'milkBanks',
    }),
    provincesID: one(provinces, {
      fields: [payload_locked_documents_rels.provincesID],
      references: [provinces.id],
      relationName: 'provinces',
    }),
    regionsID: one(regions, {
      fields: [payload_locked_documents_rels.regionsID],
      references: [regions.id],
      relationName: 'regions',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  })
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  })
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  })
);
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));

type DatabaseSchema = {
  enum_cities_municipalities_type: typeof enum_cities_municipalities_type;
  enum_hospitals_type: typeof enum_hospitals_type;
  enum_individuals_gender: typeof enum_individuals_gender;
  enum_individuals_marital_status: typeof enum_individuals_marital_status;
  enum_milk_banks_type: typeof enum_milk_banks_type;
  enum_users_role: typeof enum_users_role;
  enum_users_profile_type: typeof enum_users_profile_type;
  addresses: typeof addresses;
  avatars: typeof avatars;
  barangays: typeof barangays;
  cities_municipalities: typeof cities_municipalities;
  hospitals: typeof hospitals;
  hospitals_rels: typeof hospitals_rels;
  images: typeof images;
  images_rels: typeof images_rels;
  individuals: typeof individuals;
  individuals_rels: typeof individuals_rels;
  island_groups: typeof island_groups;
  milk_banks: typeof milk_banks;
  milk_banks_rels: typeof milk_banks_rels;
  provinces: typeof provinces;
  regions: typeof regions;
  users: typeof users;
  users_rels: typeof users_rels;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_addresses: typeof relations_addresses;
  relations_avatars: typeof relations_avatars;
  relations_barangays: typeof relations_barangays;
  relations_cities_municipalities: typeof relations_cities_municipalities;
  relations_hospitals_rels: typeof relations_hospitals_rels;
  relations_hospitals: typeof relations_hospitals;
  relations_images_rels: typeof relations_images_rels;
  relations_images: typeof relations_images;
  relations_individuals_rels: typeof relations_individuals_rels;
  relations_individuals: typeof relations_individuals;
  relations_island_groups: typeof relations_island_groups;
  relations_milk_banks_rels: typeof relations_milk_banks_rels;
  relations_milk_banks: typeof relations_milk_banks;
  relations_provinces: typeof relations_provinces;
  relations_regions: typeof relations_regions;
  relations_users_rels: typeof relations_users_rels;
  relations_users: typeof relations_users;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
